# Default values for broadcast-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ericvh/broadcast-gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  tcpPort: 50222
  nodePort: 30222

# Network configuration
network:
  udpPort: 50222
  tcpHost: "your-tcp-server.com"  # Required: Set to your target TCP endpoint
  tcpPort: 50222
  bindAddress: "0.0.0.0"
  enableFirewall: true
  firewallInterface: "any"
  reconnectDelay: 5.0

# Resource configuration
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Security context
securityContext:
  privileged: true
  runAsUser: 0

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Health checks
livenessProbe:
  tcpSocket:
    port: 50222
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  tcpSocket:
    port: 50222
  initialDelaySeconds: 5
  periodSeconds: 10
