# Default values for multicast-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/your-username/multicast-gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  tcpPort: 8888
  nodePort: 30888

# Network configuration
network:
  udpPort: 9999
  tcpPort: 8888
  bindAddress: "0.0.0.0"
  enableFirewall: true
  firewallInterface: "any"

# Resource configuration
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Security context
securityContext:
  privileged: true
  runAsUser: 0

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Health checks
livenessProbe:
  tcpSocket:
    port: 8888
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  tcpSocket:
    port: 8888
  initialDelaySeconds: 5
  periodSeconds: 10
